export const bodyParts = [
	{
		id: 0,
		part: "back",
		imgLink: require("../../assets/images/backImg.png"),
	},
	{
		id: 1,
		part: "cardio",
		imgLink: require("../../assets/images/abs.png"),
	},
	{ id: 2, part: "chest", imgLink: require("../../assets/images/chest.png") },
	{
		id: 3,
		part: "lower arms",
		imgLink: require("../../assets/images/lower-arm.png"),
	},
	{
		id: 4,
		part: "lower legs",
		imgLink: require("../../assets/images/lower-legs.png"),
	},
	{
		id: 5,
		part: "neck",
		imgLink: require("../../assets/images/neck.png"),
	},
	{
		id: 6,
		part: "shoulders",
		imgLink: require("../../assets/images/shoulderImg.png"),
	},
	{
		id: 7,
		part: "upper arms",
		imgLink: require("../../assets/images/upper-arms.png"),
	},
	{
		id: 8,
		part: "upper legs",
		imgLink: require("../../assets/images/upper-legs.png"),
	},
	{
		id: 9,
		part: "waist",
		imgLink: require("../../assets/images/waist-img.png"),
	},
];

export const equipments = [
	{ id: 0, name: "assisted" },
	{ id: 1, name: "band" },
	{ id: 2, name: "barbell" },
	{ id: 3, name: "body weight" },
	{ id: 4, name: "bosu ball" },
	{ id: 5, name: "cable" },
	{ id: 6, name: "dumbbell" },
	{ id: 7, name: "elliptical machine" },
	{ id: 8, name: "ez barbell" },
	{ id: 9, name: "hammer" },
	{ id: 10, name: "kettlebell" },
	{ id: 11, name: "leverage machine" },
	{ id: 12, name: "medicine ball" },
	{ id: 13, name: "olympic barbell" },
	{ id: 14, name: "resistance band" },
	{ id: 15, name: "roller" },
	{ id: 16, name: "rope" },
	{ id: 17, name: "skierg machine" },
	{ id: 18, name: "sled machine" },
	{ id: 19, name: "smith machine" },
	{ id: 20, name: "stability ball" },
	{ id: 21, name: "stationary bike" },
	{ id: 22, name: "stepmill machine" },
	{ id: 23, name: "tire" },
	{ id: 24, name: "trap bar" },
	{ id: 25, name: "upper body ergometer" },
	{ id: 26, name: "weighted" },
	{ id: 27, name: "wheel roller" },
];
